---
title: "project1"
output: html_document
---
```{r}
library(tibble)
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r}
#devtools::install_github(repo = "BillPetti/baseballr")
```

```{r}
## Code modified from Bill Petti's original annual Statcast scraper:
## Main change is in the column names of the fielders

annual_statcast_query <- function(season) {
  
  data_base_column_types <- 
    readr::read_csv("https://app.box.com/shared/static/q326nuker938n2nduy81au67s2pf9a3j.csv")
  
  dates <- 
    seq.Date(as.Date(paste0(season, '-03-01')),
             as.Date(paste0(season, '-12-01')), 
             by = '4 days')
  
  date_grid <- 
    tibble::tibble(start_date = dates, 
                   end_date = dates + 3)
  
  safe_savant <- 
    purrr::safely(baseballr::scrape_statcast_savant)
  
  payload <- 
    purrr::map(.x = seq_along(date_grid$start_date),
               ~{message(paste0('\nScraping week of ', date_grid$start_date[.x], '...\n'))
                 payload <- 
                   safe_savant(start_date = date_grid$start_date[.x], 
                               end_date = date_grid$end_date[.x], 
                               type = 'pitcher')
                 return(payload)
               })
  
  payload_df <- purrr::map(payload, 'result')
  
  number_rows <- 
    purrr::map_df(.x = seq_along(payload_df),
                  ~{number_rows <- 
                    tibble::tibble(week = .x, 
                                   number_rows = length(payload_df[[.x]]$game_date))
                  }) %>%
    dplyr::filter(number_rows > 0) %>%
    dplyr::pull(week)
  
  payload_df_reduced <- payload_df[number_rows]
  
  payload_df_reduced_formatted <- 
    purrr::map(.x = seq_along(payload_df_reduced), 
               ~{cols_to_transform <- 
                 c("pitcher", "fielder_2", "fielder_3",
                   "fielder_4", "fielder_5", "fielder_6", "fielder_7",
                   "fielder_8", "fielder_9")
               df <- 
                 purrr::pluck(payload_df_reduced, .x) %>%
                 dplyr::mutate_at(.vars = cols_to_transform, as.numeric) %>%
                 dplyr::mutate_at(.vars = cols_to_transform, function(x) {ifelse(is.na(x), 999999999, x)})
               character_columns <- 
                 data_base_column_types %>%
                 dplyr::filter(class == "character") %>%
                 dplyr::pull(variable)
               numeric_columns <- 
                 data_base_column_types %>%
                 dplyr::filter(class == "numeric") %>%
                 dplyr::pull(variable)
               integer_columns <- 
                 data_base_column_types %>%
                 dplyr::filter(class == "integer") %>%
                 dplyr::pull(variable)
               df <- 
                 df %>%
                 dplyr::mutate_if(names(df) %in% character_columns, as.character) %>%
                 dplyr::mutate_if(names(df) %in% numeric_columns, as.numeric) %>%
                 dplyr::mutate_if(names(df) %in% integer_columns, as.integer)
               return(df)
               })
  
  combined <- payload_df_reduced_formatted %>%
    dplyr::bind_rows()
  
  return(combined)
}
```

```{r}

#raw_statcast2024 <- annual_statcast_query(2024)
#save(raw_statcast2024, file = "raw_statcast2024.RData")
#chadwick_players <- baseballr::chadwick_player_lu()
#save(chadwick_players, file = "chadwick_players.RData")
```

```{r}
raw_data = load("raw_statcast2024.RData")
players = load("chadwick_players.RData")
```

```{r}
statcast2024 <-
  raw_statcast2024 |> 
  dplyr::filter(game_type == "R") |>
  dplyr::filter(
    strikes >= 0 & strikes < 3 & 
      balls >= 0 & balls < 4 & 
      outs_when_up >= 0 & outs_when_up < 3) |>
  dplyr::arrange(game_date, game_pk, at_bat_number, pitch_number)
```

```{r}
statcast2024 <-
  statcast2024 |>
  dplyr::mutate(
    BaseRunner = 
      paste0(1*(!is.na(on_1b)),1*(!is.na(on_2b)),1*(!is.na(on_3b)))) |>
  dplyr::rename(Outs = outs_when_up)
```


```{r}
statcast2024_small = statcast2024 %>% 
  select(pitch_type, game_date, pitcher, description, events, balls, strikes, pitch_number, pitch_name, hit_location, delta_pitcher_run_exp) %>% 
  rename(pitcher_idx = pitcher)
```

```{r}
player2024_id <-
  unique(
    c(statcast2024$batter, statcast2024$pitcher
      ))

player2024_lookup <-
  chadwick_players |>
  dplyr::filter(!is.na(key_mlbam) & key_mlbam %in% player2024_id) |>
  dplyr::mutate(
    FullName = paste(name_first, name_last),
    Name = stringi::stri_trans_general(FullName, "Latin-ASCII"))
save(player2024_lookup, file = "player2024_lookup.RData")
  
```

```{r}
allstar_pitchers_2024 <- tibble(
  name = c(
    "Tyler Anderson", "Corbin Burnes", "Garrett Crochet", "Tanner Houck", "Seth Lugo",
    "Clay Holmes", "Mason Miller", "Cole Ragans", 
    "Tarik Skubal", "Kirby Yates", "Logan Gilbert", "Emmanuel Clase", "Andrés Muñoz", "Max Fried", "Hunter Greene", "Shota Imanaga", "Reynaldo López", "Christopher Sánchez", "Paul Skenes", "Logan Webb", "Jeff Hoffman", "Tanner Scott", "Matt Strahm", "Robert Suarez", "Kyle Finnegan", "Tyler Glasnow", "Ryan Helsley", "Chris Sale", "Ranger Suárez", "Zach Wheeler"
  )
)
all_star_pitcher_lookup = player2024_lookup %>% # gets the name and idx of all star pitchers
  filter(FullName %in% allstar_pitchers_2024$name) %>% 
  rename(pitcher_idx = key_mlbam) %>% 
  select(pitcher_idx, Name)
```

```{r}
pitches_sorted = statcast2024_small %>% #sorts all pitches by game and pitch order
  arrange(pitcher_idx, game_date)
```

```{r}
pitcher_sequences <- pitches_sorted %>%
  group_by(pitcher_idx) %>% #groups by individual pitcher
  mutate(
    next1 = lead(pitch_type, 1), #finds pitch type of next pitch, if doesnt exist drops it
    next2 = lead(pitch_type, 2),
    sequence = paste(pitch_type, next1, next2, sep = "-")
  ) %>% 
  filter(!is.na(next2)) %>% 
  ungroup() %>% 
  group_by(pitcher_idx, sequence) %>% #re groups by pitcher and sequence
  summarise(
    total_delta_run_exp = sum(delta_pitcher_run_exp, na.rm = TRUE), #sums run expectancy (how is this calculated?)
    n = n(),                                   # number of times sequence occurred
    avg_delta_run_exp = mean(delta_pitcher_run_exp, na.rm = TRUE)
  ) %>%
  filter(n>50) %>% # arbitrary value, gets rid of insignificant low frequency sequences
  slice_max(order_by = avg_delta_run_exp, n=3) %>% 
  ungroup() %>% 
  mutate(
    Name = all_star_pitcher_lookup$Name[
    match(pitcher_idx, all_star_pitcher_lookup$pitcher_idx) #match the pitcher idx to a name
    ]
  ) %>% 
  filter(!is.na(Name))
```

```{r}
highest_sequence_instance <- pitches_sorted %>%
  arrange(pitcher_idx, game_date, inning, pitch_number) %>%
  group_by(pitcher_idx, game_date, at_bat_number) %>%
  mutate(
    next1 = lead(pitch_type, 1),
    next2 = lead(pitch_type, 2),
    next1_delta = lead(delta_pitcher_run_exp, 1),
    next2_delta = lead(delta_pitcher_run_exp, 2),
    sequence = paste(pitch_type, next1, next2, sep = "-"),
    total_sequence_delta = delta_pitcher_run_exp + next1_delta + next2_delta,
    .by_group = TRUE
  ) %>%
  #filter(!is.na(next2)) %>%       # keep only complete 3-pitch sequences
  ungroup() %>%
  slice_max(order_by = total_sequence_delta, n = 1, with_ties = FALSE) %>%
  mutate(
    Name = all_star_pitcher_lookup$Name[
      match(pitcher_idx, all_star_pitcher_lookup$pitcher_idx)
    ]
  ) %>%
  select(Name, pitcher_idx, game_date, pitch_number, sequence, total_sequence_delta, inning, inning_topbot, Outs, description)

highest_sequence_instance
```


